services:
  frontend:
    build:
      context: ./frontend
    container_name: my-frontend
    image: wq1a/chess-union-frontend:latest
    environment:
      - VITE_API_BASE_URL=http://83.166.247.15:8080
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - my-network
    command: ["npm", "run", "dev", "--", "--host"]

  backend:
    build:
      context: .
    image: wq1a/chess-union-backend:latest
    container_name: my-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - my-network

  db:
    image: postgres:15
    container_name: my-postgres
    environment:
      - POSTGRES_DB=chess-union-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=23111
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my-network

  redis:
    image: redis:7
    container_name: my-redis
    ports:
      - "6379:6379"
    networks:
      - my-network

  redis-insight:
    image: redis/redisinsight:latest
    container_name: my-redis-insight
    ports:
      - "5540:5540"
    depends_on:
      - redis
    networks:
      - my-network

volumes:
  postgres_data:
  redis_insight:

networks:
  my-network:
    driver: bridge