services:
  web:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: ""
    image: wq1a/chess-union-web:latest
    container_name: my-web
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - my-network
    volumes:
      # монтируем твои уже существующие сертификаты с хоста внутрь контейнера
      - /etc/ssl/nginx/chess-union.ru.chained.crt:/etc/ssl/nginx/chess-union.ru.chained.crt:ro
      - /etc/ssl/nginx/certificate.key:/etc/ssl/nginx/certificate.key:ro

  backend:
    build:
      context: .
    image: wq1a/chess-union-backend:latest
    container_name: my-backend
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: unless-stopped
    volumes:
      - profile_images:/data/profile_images
    networks:
      - my-network
    # ports наружу можно убрать (безопаснее)
    # если хочешь оставить для отладки - раскомментируй:
    # ports:
    #   - "8080:8080"

  db:
    image: postgres:15
    container_name: my-postgres
    environment:
      - POSTGRES_DB=chess-union-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=23111
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - my-network

  redis:
    image: redis:7
    container_name: my-redis
    restart: unless-stopped
    networks:
      - my-network

  redis-insight:
    image: redis/redisinsight:latest
    container_name: my-redis-insight
    ports:
      - "5540:5540"
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - my-network

volumes:
  postgres_data:
  profile_images:

networks:
  my-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1500