version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    networks:
      - my-redis-network

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    restart: always
    depends_on:
      - redis
    ports:
      - "5540:5540"
    networks:
      - my-redis-network

volumes:
  redis_insight:

networks:
  my-redis-network:
    driver: bridge