spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/chess-union-db
    username: postgres
    password: 23111
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  application:
    name: ChessUnion
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    clean-disabled: true

jwt:
  lifetime: 30m
  secret: 90384fj304jf09j09fj3409fj3094fj9sjfP3dj8DDikSDJ39dJD39d3jdd
logging:
  level:
    org:
      hibernate: DEBUG
      flywaydb: DEBUG
      springframework:
        orm:
          jpa: DEBUG
        transaction: DEBUG
        security: DEBUG

server:
  port: 8080