CREATE TABLE users(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    username varchar(128) NOT NULL UNIQUE,
    password varchar(128) NOT NULL
);


CREATE TABLE roles(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(128)
);

CREATE TABLE users_roles(
    user_id bigint REFERENCES users(id),
    role_id int REFERENCES roles(id),
    PRIMARY KEY (user_id, role_id)
);




--INSERTS ........

INSERT INTO roles(name) values ('USER_ROLE'),
                               ('ADMIN_ROLE');