CREATE TABLE users(
                      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                      name varchar(128),
    password varchar(128)
);

CREATE TABLE roles(
                      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                      name varchar(128)
);

CREATE TABLE users_roles(
                            user_id INTEGER REFERENCES users(id),
                            role_id INTEGER REFERENCES roles(id),
                            PRIMARY KEY (user_id, role_id)
);