CREATE TABLE matches
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    white_player_id INTEGER,
    black_player_id INTEGER,
    tournament_id   INTEGER,
    round_number    INTEGER,
    result          DOUBLE PRECISION,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_matches PRIMARY KEY (id)
);

CREATE TABLE players
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    score         DOUBLE PRECISION,
    color_balance INTEGER,
    user_id       INTEGER,
    rating        DOUBLE PRECISION,
    tournament_id INTEGER,
    had_bye       BOOLEAN,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_players PRIMARY KEY (id)
);

CREATE TABLE tournaments
(
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    current_round         INTEGER,
    max_amount_of_players INTEGER,
    min_amount_of_players INTEGER,
    stage                 VARCHAR(255),
    created_at            TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tournaments PRIMARY KEY (id)
);

ALTER TABLE users
    ADD created_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE users
    ADD email VARCHAR(50);

ALTER TABLE users
    ADD first_name VARCHAR(50);

ALTER TABLE users
    ADD last_name VARCHAR(50);

ALTER TABLE users
    ADD rating DOUBLE PRECISION;

ALTER TABLE users
    ADD username VARCHAR(128);

ALTER TABLE users
    ALTER COLUMN first_name SET NOT NULL;

ALTER TABLE users
    ALTER COLUMN last_name SET NOT NULL;

ALTER TABLE users
    ALTER COLUMN rating SET NOT NULL;

ALTER TABLE users
    ALTER COLUMN username SET NOT NULL;

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE matches
    ADD CONSTRAINT FK_MATCHES_ON_BLACK_PLAYER FOREIGN KEY (black_player_id) REFERENCES players (id);

ALTER TABLE matches
    ADD CONSTRAINT FK_MATCHES_ON_TOURNAMENT FOREIGN KEY (tournament_id) REFERENCES tournaments (id);

ALTER TABLE matches
    ADD CONSTRAINT FK_MATCHES_ON_WHITE_PLAYER FOREIGN KEY (white_player_id) REFERENCES players (id);

ALTER TABLE players
    ADD CONSTRAINT FK_PLAYERS_ON_TOURNAMENT FOREIGN KEY (tournament_id) REFERENCES tournaments (id);

ALTER TABLE players
    ADD CONSTRAINT FK_PLAYERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE users
    DROP COLUMN name;

ALTER TABLE roles
    ALTER COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE users
    ALTER COLUMN password SET NOT NULL;