create table player (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(128) NOT NULL UNIQUE,
    rating int check(rating > 0),
    score numeric,
    color_balance int,
    had_bye boolean
);

create table game(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    white_player bigint references player(id),
    black_player bigint references player(id),
    tournament bigint references tournament(id),
    round_number int
);

create table tournament(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    current_round int not null default 0
);
